version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes: # <-- Add this
      - /app/node_modules
      - ./frontend:/app # Maps your host machine's frontend code to / in the container
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    # network_mode: "host"
    volumes: # <-- Add this
      - ./backend:/app # Maps your host machine's backend code to /app in the container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  filebeat:
    build:
      context: ./filebeat_custom
    command: filebeat -e
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "backend"
