version: "3"

services:
  frontend:
    image: 309329557868.dkr.ecr.eu-central-1.amazonaws.com/my-frontend:latest
    ports:
      - "80:80"

  backend:
    image: 309329557868.dkr.ecr.eu-central-1.amazonaws.com/my-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  filebeat:
    image: 309329557868.dkr.ecr.eu-central-1.amazonaws.com/my-filebeat:latest
    command: filebeat -e
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "backend"

