# render.yaml

services:
  - type: web
    runtime: docker
    name: frontend
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: REACT_APP_API_URL
        value: https://localhost:8000/ # Replace with your actual backend URL

  - type: web
    runtime: docker
    name: backend
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: docker build -t backend -f Dockerfile .

  - type: web
    runtime: docker
    name: redis
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: docker build -t redis -f Dockerfile .

databases:
  - name: app
    plan: free
