# render.yml

services:
  - type: web
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /

  - type: web
    name: backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: redis
    startCommand: docker run -d redis:latest

  - type: web
    name: filebeat
    startCommand: filebeat -e
