# render.yaml

services:
  - type: docker
    name: frontend
    dockerfilePath: frontend/Dockerfile
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://localhost:8000/ # Replace with your actual backend URL

  - type: docker
    name: backend
    dockerfilePath: backend/Dockerfile
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379

  - type: docker
    name: redis
    dockerfilePath: docker-compose.yml
    buildCommand: docker-compose build
    startCommand: docker-compose up -d
    healthCheckPath: /

databases:
  - name: redis
    plan: free
