# render.yaml

services:
  - type: web
    runtime: docker
    name: frontend
    rootDir: frontend
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: cd frontend && npm install && npm run build
    envVars: # Replace with your actual backend URL
      - key: PORT
        value: 8000

  - type: web
    runtime: docker
    name: backend
    rootDir: ./backend
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: docker build -t backend -f Dockerfile .
    envVars: # Replace with your actual backend URL
      - key: PORT
        value: 3000

  - type: redis
    name: redis
    ipAllowList: []
    plan: free


databases:
  - name: app
    plan: free
