# render.yml

services:
  - name: frontend
    type: web
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /

  - name: backend
    type: web
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - name: redis
    type: web
    image: redis:latest

  - name: filebeat
    type: web
    startCommand: filebeat -e
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    dependsOn:
      - backend
