# Use an official Python runtime as the base image
FROM python:3.11.4-alpine

# Set the working directory in the container
WORKDIR /app


# Copy the requirements file into the container
COPY requirements.txt .

# Install FastAPI dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend directory into the container
COPY . .

# Copy entrypoint.sh and make it executable if present
COPY entrypoint.sh /app/entrypoint.sh
RUN [ -f /app/entrypoint.sh ] && chmod +x /app/entrypoint.sh || true

# Set the ENTRYPOINT to your script
ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]


# Set the command to run your application using Uvicorn
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "10000", "--reload"]

# CMD ["sh", "-c", "uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"]